### ISSUE TITLE
Icons missing and/or out of alignment on certain pages

### ISSUE THREAD

**Issue by tonyjbutler** [gjb2048/moodle-theme_essential#838] opened 2017-07-14 09:55 UTC
In Moodle 3.3.1 with Essential 3.3.0.3 (latest code from master):

- On Assignment pages the editing icons in both the navbar actionmenu and the settings block are all missing.

![assign_page_actionmenu](https://user-images.githubusercontent.com/1395170/28207770-c594f0ea-6882-11e7-9892-a2530a4f75c8.png) ![assign_page_settings](https://user-images.githubusercontent.com/1395170/28207769-c5902704-6882-11e7-9e5e-138d31378bd7.png)

- On the course Participants page the navbar actionmenu items are out of alignment and some of their icons are missing.

![participants_page_actionmenu](https://user-images.githubusercontent.com/1395170/28207768-c58ecd32-6882-11e7-8db2-87e3496355c5.png)

**Comment by gjb2048** [comment] 2017-07-14 10:00
Latest from GitHub as from the changes of last night?

**Comment by tonyjbutler** [comment] 2017-07-14 10:02
Yes, I've just pulled those in the hope they would include the fix.

**Comment by gjb2048** [comment] 2017-07-14 10:07
A fix for a specific issue?  If so, which one please Tony?

**Comment by tonyjbutler** [comment] 2017-07-14 10:10
No, I just made sure I pulled the latest commits before reporting this issue, in case some other fix happened to have fixed this too.

**Comment by gjb2048** [comment] 2017-07-14 10:11
So was this an issue I did not know about?

**Comment by tonyjbutler** [comment] 2017-07-14 10:13
I couldn't find another report for it.

**Comment by gjb2048** [comment] 2017-07-14 10:16
So it is another issue I was not aware of?  Did you notice it before I changed to the new notifications and messaging menu system in the navbar which pulls in the 'plugin' custom menu?

**Comment by gjb2048** [comment] 2017-07-14 10:20
Or I might be wrong as could be the 'context_header_settings_menu' which was there before.  Also in Boost there is an issue with missing icons.

**Comment by tonyjbutler** [comment] 2017-07-14 10:20
As far as I can tell this is an issue that you were not previously aware of. I noticed it before pulling last night's commits, but wanted to double check that I was running the latest code before reporting it. So I pulled, cleared the caches, verified that it was still an issue and then reported it.

**Comment by gjb2048** [comment] 2017-07-14 10:22
Ok, so is Flat Navigation off please?

**Comment by tonyjbutler** [comment] 2017-07-14 10:28
Yes, flat navigation off.

**Comment by gjb2048** [comment] 2017-07-14 10:28
With the assignment pages the icons are missing in Boost, so a core issue for that: 
![boost_assign](https://user-images.githubusercontent.com/1058419/28208808-81b4e542-6887-11e7-909d-c0dae746f3a8.png)

**Comment by tonyjbutler** [comment] 2017-07-14 10:28
Aha, OK.

**Comment by gjb2048** [comment] 2017-07-14 10:29
So in Essential this will be true of the Administration menu.  Issue looks like icon replacement as classes have 'fa-fw fa-fw' and no icon class.

**Comment by tonyjbutler** [comment] 2017-07-14 10:30
Yes, I'd been trying to work out what 'fa-fw' meant, as there is no such icon.

**Comment by tonyjbutler** [comment] 2017-07-14 10:31
So Essential is based on BS4 now?

**Comment by gjb2048** [comment] 2017-07-14 10:31
fa-fw is a FontAwesome helper class.  BS4?  Why do you say and think that?

**Comment by tonyjbutler** [comment] 2017-07-14 10:32
Because it is inheriting Boost issues.

**Comment by gjb2048** [comment] 2017-07-14 10:33
Boost participants:

![boost_p](https://user-images.githubusercontent.com/1058419/28208939-2cb6ffb6-6888-11e7-8a06-449cd92bc9c1.png)

**Comment by gjb2048** [comment] 2017-07-14 10:33
Boost is not just BS4 its templating and PHP etc. with the FontAwesome icon system, so nothing to do with BS4 but everything to do with the generation of the markup.

**Comment by tonyjbutler** [comment] 2017-07-14 10:34
Right, OK.

**Comment by tonyjbutler** [comment] 2017-07-14 10:35
So this will be fixed by a core fix.

**Comment by gjb2048** [comment] 2017-07-14 10:35
This smells of one core change.

**Comment by gjb2048** [comment] 2017-07-14 10:36
It would only be fixed by core if:

a) They know about it.
b) It can be replicated in a core thing - Boost.

**Comment by gjb2048** [comment] 2017-07-14 10:37
Marked as core issue but I'll see if I can fix locally.  And I'm not happy with the alignments anyway.

**Comment by tonyjbutler** [comment] 2017-07-14 10:38
Thanks Gareth.

**Comment by gjb2048** [comment] 2017-07-14 10:44
Note to self:

.block_navigation .block_tree p.hasicon {
    text-indent: -21px;
    padding-left: 21px;  <-----
}

M3.3 and M3.2 not M3.1.

**Comment by gjb2048** [comment] 2017-07-14 10:50
Ok, stupid change to 'fa-fw' was made in https://tracker.moodle.org/browse/MDL-58808 -> https://github.com/moodle/moodle/commit/57ea73d02c0d431060c282a885e8c5852c12f5ba#diff-a4dcc10cfefa7c3fa24a187a61283fa1.

**Comment by gjb2048** [comment] 2017-07-14 10:51
Do you have a Moodle tracker account Tony?

**Comment by tonyjbutler** [comment] 2017-07-14 10:52
Sure do.

**Comment by gjb2048** [comment] 2017-07-14 10:55
In that case, please would you be so kind as to raise an issue about the missing icons on the Boost theme in relation to it being a regression caused by MDL-58808 as pragmatically I think I'm perceived by Damyon as a 'pain in the ****' so he'll no longer take any notice of me.

**Comment by tonyjbutler** [comment] 2017-07-14 10:55
OK, will do. ;-)

**Comment by gjb2048** [comment] 2017-07-14 10:59
Thank you :) - please do let me know the MDL and I'll vote for it.

**Comment by gjb2048** [comment] 2017-07-14 10:59
BTW, its only M3.3 and master issue.  MDL-58808 only went there.

**Comment by tonyjbutler** [comment] 2017-07-14 10:59
Cheers.

**Comment by tonyjbutler** [comment] 2017-07-14 14:24
https://tracker.moodle.org/browse/MDL-59545

**Comment by gjb2048** [comment] 2017-07-14 21:58
Hi Tony,

I've worked out a local fix to put the icon back.  Testing ATM.

G

**Closed** 2017-07-16 10:21 UTC
Labels: Bug, Core issue, M3.3
