### ISSUE TITLE
Moodle upgrade too long with enablecategorycti=1 and many categories

### ISSUE THREAD

**Issue by carreraj** [gjb2048/moodle-theme_essential#680] opened 2016-06-22 06:51 UTC
We have 1400 categories in our test machine (and more than 7000 in production). When  enablecategorycti is enabled (wich is by default), any moodle upgrade ( for any plugin) takes up to 20 minutes instead of 40 seconds. 
Category course title images form reaches timeouts before can get loaded.

**Comment by gjb2048** [comment] 2016-06-22 07:39
So, turn it off for upgrade and when you turn it back on again the database values should still be there.

**Comment by gjb2048** [comment] 2016-06-22 07:41
P.s. How do you know it is that setting?  Have you benchmarks with it off?

**Comment by carreraj** [comment] 2016-06-22 08:56
I turned  it off (through database, as form won't load) and upgrades went down again from 19-20 minutes to 30-50 seconds. With lots of categories this feature results unusable, so I think that it should be disabled by default (and even limited for a number of categories).
On upgrades iteration over 6 properties x 1400 categories  takes a long time.

**Comment by gjb2048** [comment] 2016-06-22 09:16
If it is a bug then its down to a core call.  Might be a way to turn off the call for admins when the state is upgrading.

**Comment by gjb2048** [comment] 2016-06-22 09:17
However 1400 categories is overkill!  I wonder how many sites have that many.

**Comment by carreraj** [comment] 2016-06-22 09:39
We use one category for each academic year, inside a category for each school or college and inside one for each degree or study. For Course 2015-2016 that is 595 categories.
We keep up to three years in main site (minimum 2 years) so that's 1200-1800 categories. Overkill? may be, but organized :)

**Comment by gjb2048** [comment] 2016-06-22 11:19
Several things going on here:

1. This could be running slow on upgrade: https://github.com/gjb2048/moodle-theme_essential/blob/master/settings.php#L2023
2. 
3. For lots of categories need to consider breaking down with sub-settings pages at least top level: https://github.com/gjb2048/moodle-theme_essential/blob/master/settings.php#L1942 so that a page load of 1400 * 7 settings clearly does not break things.

**Comment by gjb2048** [comment] 2016-06-22 12:19
I'm beginning to think that given https://github.com/gjb2048/moodle-theme_essential/blob/master/classes/output/core_renderer.php#L361-L362 and https://github.com/gjb2048/moodle-theme_essential/blob/master/classes/toolbox.php#L438-L506 that it might be better to have a single means based upon https://github.com/gjb2048/moodle-theme_essential/blob/master/classes/toolbox.php#L438-L506 that knows the depth and can make a title string that includes the parents as it does now but would then allow for sub-pages.

**Comment by relecand** [comment] 2016-06-30 12:25
Hi Gareth,

some issue here with 2000+ categories. Essential 2.9.1.13

All the best,

Christian

**Comment by gjb2048** [comment] 2016-06-30 21:06
Hi Christian,

Thanks but I've not released 2.9.1.13 yet as its in development.

Gareth

**Comment by gjb2048** [comment] 2016-06-30 21:11
Does anybody here use 'Category icons'?

**Comment by carreraj** [comment] 2016-07-01 08:04
We don't use it. We could think about using different configurations for first level categories (in our schema are academic years) but it's not a must (performance is the must)

**Comment by gjb2048** [comment] 2016-07-01 15:54
This is tricky.

**Comment by gjb2048** [comment] 2016-07-01 16:26
What's the deadline for migrating to M3.1 please?

**Comment by gjb2048** [comment] 2016-07-01 16:32
Ok, this: https://github.com/gjb2048/moodle-theme_essential/commit/5673c670451ca6f8ba78340d39ecb1ce99073680 improves things by separating out the categories into their own pages per top level category.  And 'no' there is no way to have sub-setting pages - core API does not support it.

**Comment by carreraj** [comment] 2016-07-01 17:46
We will migrate production (actually a 2.8) on the second half of July. 
There are some teachers testing  moodle 3.0  and 3.1 (with latest 
essential theme each one). The migrations will be to either one, 
depending on the test.
(It looks like it will be 3.1, as we actually don't use category theme 
neither category icons, and disabling them keeps performance ok)


El 2016-07-01 18:26, Gareth J Barnard escribió:
> What's the deadline for migrating to M3.1 please?
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the
> thread [2].
> 
> 	*
> 
> Links:
> ------
> [1]
> https://github.com/gjb2048/moodle-theme_essential/issues/680#issuecomment-229989812
> [2]
> https://github.com/notifications/unsubscribe/ABnrLXS44yeMxofB4zjg_8rU9G8s7G84ks5qRT-cgaJpZM4I7dUV

-- 
Juan Carrera

**Comment by adamtppaw** [comment] 2016-07-07 10:58
Hi, in our organisation we have noticed a semi "hangup" of moodle during upgrade the theme from moodle 3.0 to 3.1, We don't use course category images. Our admin thought it is hangup end decided to uninstall the theme and install again. It was fast. But during first attampt to the theme settings Moodle was frozen for few minutes until I was able to set anything in the form.

**Comment by gjb2048** [comment] 2016-07-07 12:45
Thanks.  This will be fixed in the next release.

**Comment by gjb2048** [comment] 2016-07-07 17:38
Ok, I've noticed when I bump versions that it takes a long time.  However, this happened long before I wrote the course category functionality.  Therefore do you have concrete evidence that it is the functionality?

**Comment by gjb2048** [comment] 2016-07-17 17:22
Also noticed that other software was causing PHP non-thread safe to run slowly.

**Comment by carreraj** [comment] 2016-07-18 06:25
In our University bumping from 2.8 to 3.1 went smoothly.

**Comment by gjb2048** [comment] 2016-08-09 17:16
Ok, my page loads can be slow, so been investigating in M3.1 and cannot find evidence.  So I turned on MySQL general logging 'general-log=1' in the my.ini file and found a big time difference with:

```
2016-08-09T17:02:29.751331Z   19 Query	SELECT c.id,c.category,c.sortorder,c.shortname,c.fullname,c.idnumber,c.startdate,c.visible,c.groupmode,c.groupmodeforce,c.cacherev,c.summary,c.summaryformat , ctx.id AS ctxid, ctx.path AS ctxpath, ctx.depth AS ctxdepth, ctx.contextlevel AS ctxlevel, ctx.instanceid AS ctxinstance
              FROM mdl_course c
              JOIN (SELECT DISTINCT e.courseid
                      FROM mdl_enrol e
                      JOIN mdl_user_enrolments ue ON (ue.enrolid = e.id AND ue.userid = '2')
                     WHERE ue.status = '0' AND e.status = '0' AND ue.timestart < 1470762100 AND (ue.timeend = 0 OR ue.timeend > 1470762100)
                   ) en ON (en.courseid = c.id)
           LEFT JOIN mdl_context ctx ON (ctx.instanceid = c.id AND ctx.contextlevel = '50')
             WHERE c.id <> '1'
          ORDER BY c.visible DESC,c.sortorder ASC
2016-08-09T17:03:04.709808Z   19 Query	SELECT DISTINCT h.id, h.wwwroot, h.name, a.sso_jump_url, a.name as application
```

So, a whopping 34 seconds, but that query is 'get_course_records' in coursecatlib.php not used by the theme.

Therefore please do turn on query logging and identify with evidence where the issue is.

**Comment by gjb2048** [comment] 2016-08-09 17:22
The query that Essential is running is only taking one tenth of a second and is called once:

```
2016-08-09T17:02:26.882650Z   19 Query	SELECT id, name, depth, path FROM mdl_course_categories   ORDER BY sortorder
2016-08-09T17:02:27.076862Z   19 Query	SELECT * FROM mdl_context WHERE contextlevel = '50' AND instanceid = '1'
```

as the results are stored as 'static'.

**Comment by gjb2048** [comment] 2016-08-13 17:50
Running a separate installation (MoodleBug) and cannot replicate, however, how can I autogenerate 700 categories?

**Comment by gjb2048** [comment] 2016-11-11 12:40
Still no evidence to support this.

**Comment by gjb2048** [comment] 2016-11-15 12:20
When updating I've noticed that the web server process reads the files in the 'node_modules' folder contained within the theme (and others) - do you have this folder?  So many files so must slow things down.

**Comment by gjb2048** [comment] 2016-11-27 18:50
Hi @carreraj,

Any news / information on this or I'll close it?

Kind regards,

Gareth

**Comment by carreraj** [comment] 2016-12-02 08:12
Hi Gareth,
 I don't have any node_modules folder on my systems. 
As I disabled enablecategorycti (through database as admin/settings.php?section=theme_essential_categorycti times out when enabled) in all our environments I don't have any new information about performance when upgrading.
I understand that we have too many categories to customize them. As we are not the only ones, could be enablecategorycti disabled by default? (Maybe a couple of words  about  not enabling it with hundreds of categories would help)
Kind regards,

Juan

**Comment by gjb2048** [comment] 2016-12-02 13:11
Hi Juan,

Thank you for your response.  I'll consider changing the default on the setting.  But I won't change the text until I can reproduce the issue and know for certain that it is the functionality causing the issue and not something else.  I've tried lots of things and no evidence points to the code in Essential causing a problem.

Gareth

**Comment by gjb2048** [comment] 2016-12-02 15:50
Looking at the code 'enablecategorycti' already has a default of 'false', so what are you on about?

**Comment by carreraj** [comment] 2016-12-12 10:46
Sorry Gareth, I missed you already changed it on 9bb639e11f2b53ce8c16f6b32a7ad2066564ef5a
it's enough for me. 
Thanks,

Juan

**Comment by gjb2048** [comment] 2017-03-14 12:26
Ok, updating on M3.1 still taking ages despite enablecategorycti being on in the UI, then turned off via the DB and then a 'purge all caches'.  I think the only way to get to the bottom of this is performance analysis: https://tjhunt.blogspot.co.uk/2013/05/performance-testing-moodle.html

**Comment by gjb2048** [comment] 2017-03-14 13:01
Harder than I thought: https://moodle.org/mod/forum/discuss.php?d=349120#p1408540.

**Comment by gjb2048** [comment] 2017-06-29 14:21
Hi,

Is this still an issue?

Kind regards,

Gareth

**Comment by adamtppaw** [comment] 2017-06-29 20:23
Hi,
We will have an opportunity to check it in third week of july. We don't use category icons, but have large site and last year we noticed very long upgrade related to this theme .
Adam

**Comment by gjb2048** [comment] 2017-06-29 20:28
Hi Adam,

Thank you.  I have done a bit of analysis with a performance tool and did pin it down to a bit of core code that read the directories of the whole installation.  Therefore I think having 'node_module' folders during the upgrade could be the culprit but need peer confirmation.

Thanks,

Gareth

**Comment by gjb2048** [comment] 2018-06-12 10:37
@carreraj Still an issue?

**Comment by carreraj** [comment] 2018-06-12 14:46
Hi Gareth,
When I check enablecategorycti and save through web interface  that page won't even load back. I can't load nofifications either. To get notifications back I have to set enablecategorycti = 0 in database and purge caches.
I don't have any updates pending, but ass soon as there are any I'll turn on enablecategorycti in database and try a cli upgrade.
Juan

**Comment by gjb2048** [comment] 2018-06-12 16:19
Hi Juan,

Do you have any node_modules directories?

G

**Comment by carreraj** [comment] 2018-06-13 11:44
Hi Gareth,
Under /lib/yuilib/3.17.2/ there are some node-* directories. Are those what you mean?
Today I'm updating a moodle plugin. Previously i've set enablecategorycti to one in mdl_config_plugins table. Cli upgrade has been running 20 minutes so far and it's not over. Usually takes 1 minute.
Strace shows something like this:
``
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "i4424textbackgroundopactity\0030.8\""..., 4565, MSG_DONTWAIT, NULL, NULL) = 4565
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, ".8\"\0\0&\31categorycti4473textcolour"..., 4565, MSG_DONTWAIT, NULL, NULL) = 4565
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "our\7#000000\32\0\0\227\25categorycti4526h"..., 4565, MSG_DONTWAIT, NULL, NULL) = 3760
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "ght\003200,\0\0\364#categorycti4549textb"..., 805, MSG_DONTWAIT, NULL, NULL) = 805
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "54height\003200,\0\0\10#categorycti4554"..., 4565, MSG_DONTWAIT, NULL, NULL) = 4565
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "598textcolour\7#000000\32\0\0y\25catego"..., 4565, MSG_DONTWAIT, NULL, NULL) = 4565
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "egorycti4627height\003200,\0\0\352#categ"..., 4565, MSG_DONTWAIT, NULL, NULL) = 4565
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "tegorycti4686textbackgroundcolou"..., 4565, MSG_DONTWAIT, NULL, NULL) = 1884
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "i4697textcolour\7#000000\32\0\0\211\25cate"..., 2681, MSG_DONTWAIT, NULL, NULL) = 2681
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "lour\7#ffffff*\0\0\313%categorycti4714"..., 4565, MSG_DONTWAIT, NULL, NULL) = 4565
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "789textbackgroundopactity\0030.8\"\0\0"..., 4565, MSG_DONTWAIT, NULL, NULL) = 4565
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "\"\0\0\254\31categorycti4853textcolour\7#"..., 4565, MSG_DONTWAIT, NULL, NULL) = 4565
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "r\7#00000", 4565, MSG_DONTWAIT, NULL, NULL) = 8
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "0\32\0\0\35\25categorycti4882height\003200,"..., 4557, MSG_DONTWAIT, NULL, NULL) = 4557
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "\0\0\222\26categoryctimageurl3005\0\30\0\0\223\26"..., 4565, MSG_DONTWAIT, NULL, NULL) = 4565
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "\0005\26categoryctimageurl3168\0\30\0\0006\26c"..., 4565, MSG_DONTWAIT, NULL, NULL) = 4565
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "\330\26categoryctimageurl3331\0\30\0\0\331\26ca"..., 4565, MSG_DONTWAIT, NULL, NULL) = 2697
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "yctimageurl3427\0\30\0\0009\26categorycti"..., 1868, MSG_DONTWAIT, NULL, NULL) = 1868
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "\26categoryctimageurl3494\0\30\0\0|\26cat"..., 4565, MSG_DONTWAIT, NULL, NULL) = 4565
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "categoryctimageurl3657\0\30\0\0\37\26cate"..., 4565, MSG_DONTWAIT, NULL, NULL) = 4565
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
``
Upgrading process shows success in plugin uprade but it doesn't ends. Loks like it is doing some repetitive task on categories (There are more than one thousnad in this server).

Kind regards,
Juan

**Comment by carreraj** [comment] 2018-06-13 12:56
Hi Gareth,
No node_modules in our moodle. 
Upgrading took 84m vs 54s with enablecategoryctl=0. There are 1994 categories in this moodle instance.

juan

**Comment by nise** [comment] 2018-12-06 13:57
Where do I find enablecategorycti in the database? Is it still present in M3.5?

**Comment by gjb2048** [comment] 2018-12-06 14:07
Its a setting in settings.php and thus in the appropriate table as such for plugin settings.

**Comment by gjb2048** [comment] 2018-12-06 14:08
Also this is really annoying as you've asked me a question that is separate to the actual issue.  Grrrr.

**Comment by gjb2048** [comment] 2019-04-16 16:14
Closing as no more evidence to support issue.

**Closed by gjb2048** 2019-04-16 16:14 UTC
Labels: Cannot reproduce
