### ISSUE TITLE
'Undefined index' error appearing

### ISSUE THREAD

**Issue by vaughany** [gjb2048/moodle-theme_essential#557] opened 2015-10-09 13:19 UTC
Hi there. Just started using 2.9.1.1 and received the following error:

`Notice: Undefined index: alt in /theme/essential/classes/core_renderer.php on line 962`

It appears on a course page immediately before a news forum (but the topic section also contained resource modules and folder modules), and nine times immediately before nine assign instances (that topic section contained nothing else).

**Comment by gjb2048** [comment] 2015-10-09 13:57
That code has been in place for ages without any issue or me noticing anything.  Please describe any changes you have made and all third party plugins and a screen shot of the problem please.

**Comment by gjb2048** [comment] 2015-10-09 15:40
Cannot reproduce.  More information as specified required or will close.

**Comment by vaughany** [comment] 2015-10-09 23:43
No changes to the theme at all. It's as-installed. I didn't realise until now that you need editing turned on though.

![error1](https://cloud.githubusercontent.com/assets/381767/10407673/fe883620-6ee5-11e5-9ff6-bb8289abb611.png)
![error2](https://cloud.githubusercontent.com/assets/381767/10407674/fe89f38e-6ee5-11e5-9886-e7f95c3ff63d.png)

Bit list of additional plugins, as requested:

Activity modules
Attendance Register
mod_attendanceregister
Bootstrap elements
mod_bootstrapelements
Certificate
mod_certificate
Checklist
mod_checklist
Game
mod_game
HotPot module
mod_hotpot
Journal
mod_journal
Quizventure
mod_quizgame
Realtime quiz
mod_realtimequiz
Scheduler
mod_scheduler
Slideshow
mod_slideshow

Assignment / Submission plugins
Planet eStream Submission Plugin
assignsubmission_estream
Mahara portfolio
assignsubmission_mahara

Assignment / Feedback plugins
Mahara feedback
assignfeedback_mahara
Upload PDF
assignment_uploadpdf

HotPot module / Output formats
Hot Potatoes output formats
hotpotattempt_hp
HTML output formats
hotpotattempt_html
Qedoc output formats
hotpotattempt_qedoc

HotPot module / Source files
Hot Potatoes source files
hotpotsource_hp
HTML source files
hotpotsource_html
Qedoc source files
hotpotsource_qedoc

HotPot module / Reports
Statistical analysis report
hotpotreport_analysis
Click trail report
hotpotreport_clicktrail
Overview report
hotpotreport_overview
Responses report
hotpotreport_responses
Scores report
hotpotreport_scores

Blocks
Accessibility
block_accessibility
Checklist
block_checklist
Configurable Reports
block_configurable_reports
Course contents
block_course_contents
Leap
block_leap
Navigation Buttons
block_navbuttons
Progress Bar
block_progress
Sharing Cart
block_sharing_cart
Shibboleth Login
block_shibboleth_login
Twitter Search Block
block_twitter_search

Question types
Combined
qtype_combined
Drag and drop onto image
qtype_ddimageortext
Drag and drop markers
qtype_ddmarker
Drag and drop into text
qtype_ddwtos
Select missing words
qtype_gapselect

Text filters
FontAwesome Icon Filter.
filter_fontawesome
Planet eStream iFrame Filter
filter_planetestream

Enrolment methods
Forced Enrolment
enrol_forced
Leap enrolments
enrol_leap
RESTian XML
enrol_restxml

Admin tools
Rebuild Course Cache
tool_rebuildcoursecache
Reset MyMoodle
tool_resetmymoodle
SDC Tools
tool_sdctools

Course formats
Columns format
format_columns
Flexible sections format
format_flexsections
Grid format
format_grid

Reports
Ad-hoc database queries
report_customsql
Overview statistics
report_overviewstats

Grade export methods
Checklist
gradeexport_checklist

Gradebook reports
Multi Grader report
gradereport_multigrader

Advanced grading methods
BTEC marking
gradingform_btec

Repositories
Cats
repository_catapi
Planet eStream Search
repository_planetestream

Themes
Aardvark
theme_aardvark
Archaius
theme_archaius
Essential
theme_essential

Local plugins
Code checker
local_codechecker
Fullscreen toggle button
local_fullscreen
Leap Web Services
local_leapwebservices
Login as
local_loginas
Moodle PHPdoc check
local_moodlecheck
Profile switches
local_profileswitches

**Comment by gjb2048** [comment] 2015-10-10 11:38
Thank you for the extreme amount of extra information Paul, I'll see if I can replicate.  But I don't think I'll have time to replicate that entire environment.  It could be any icon from any of them on the page.  Might need a 'view source' to see which one is missing the 'alt' attribute on the tag in the mark-up.

**Comment by gjb2048** [comment] 2015-10-10 11:58
Can now reproduce when editing is on.  Very, very odd that has not happened before.

**Comment by gjb2048** [comment] 2015-10-10 12:02
Icon with issue is 'groupn' which was implemented recently in #535.

**Comment by gjb2048** [comment] 2015-10-10 12:18
```
[10-Oct-2015 13:15:07 Europe/London] PHP Notice:  Undefined index: alt in F:\moodledev\moodle29\theme\essential\classes\core_renderer.php on line 962
[10-Oct-2015 13:15:07 Europe/London] pix_icon Object
(
    [pix] => i/groupn
    [component] => moodle
    [attributes] => Array
        (
            [class] => iconsmall
        )

)
```

**Comment by gjb2048** [comment] 2015-10-10 12:49
Fixed in: https://github.com/gjb2048/moodle-theme_essential/commit/dc18d3c775fe5112ef148df5fd3e10275dd4ac58

**Closed** 2015-10-10 12:48 UTC
Labels: Bug

**Comment by vaughany** [comment] 2015-10-12 07:51
:+1:
