### ISSUE TITLE
Odd bullets

### ISSUE THREAD

**Issue by bdereski** [gjb2048/moodle-theme_essential#875] opened 2018-07-25 12:47 UTC
After loading the last Essential Theme update I am seeing odd misalligned bullets in the Course and categories screen.

![image](https://user-images.githubusercontent.com/41687406/43201718-e58960aa-8fde-11e8-96f1-173d61249ec3.png)

**Comment by gjb2048** [comment] 2018-07-25 12:48
Latest?

**Comment by bdereski** [comment] 2018-07-25 12:49
3.5

**Comment by gjb2048** [comment] 2018-07-25 12:50
Moodle or Essential?

**Comment by bdereski** [comment] 2018-07-25 12:51
Both Moodle 3.5 and the Essential Theme for 3.5

**Comment by gjb2048** [comment] 2018-07-25 12:52
Ok, what version of the Essential theme please?

**Comment by gjb2048** [comment] 2018-07-25 12:54
And what is the URL of the page causing the issue please?

**Comment by gjb2048** [comment] 2018-07-25 12:54
What other plugins do you have installed?  What custom CSS have you got?

**Comment by bdereski** [comment] 2018-07-25 13:00
![image](https://user-images.githubusercontent.com/41687406/43202193-733a5fd4-8fe0-11e8-888f-0b88c8f39eeb.png)
I don't have the answers to your other questions.  Everything was displaying fine after loading Moodle 3.5, but the Essential Theme was not available at that version yet.  Once version 3.5.0.1 was available we loaded that and now I see this display.

**Comment by gjb2048** [comment] 2018-07-25 13:04
I cannot replicate on the 'Course and category management' page being like '/course/management.php?categoryid=1'.

**Comment by bdereski** [comment] 2018-07-25 13:05
https://devpdc.skyward.com/course/management.php?categoryid=2

**Comment by gjb2048** [comment] 2018-07-25 13:07
I can't reach that URL and its the same page as the one I've described and cannot replicate.  Assuming under 'Course categories'?

**Comment by bdereski** [comment] 2018-07-25 13:08
correct, under course catagories

**Comment by gjb2048** [comment] 2018-07-25 16:09
Ok, can replicate, odd list-style-type cannot find where.

**Comment by gjb2048** [comment] 2018-07-25 16:16
Happens in Clean too.

**Comment by gjb2048** [comment] 2018-07-25 16:53
FYI: https://tracker.moodle.org/browse/MDL-62986

**Comment by bdereski** [comment] 2018-07-25 20:40
Thank you!

**Comment by gjb2048** [comment] 2018-07-26 08:36
My issue is a duplicate of https://tracker.moodle.org/browse/MDL-62807.

**Comment by gjb2048** [comment] 2018-07-28 11:54
Will be fixed in core, closing.

**Closed by gjb2048** 2018-07-28 11:54 UTC
Labels: Bug, Core issue
