### ISSUE TITLE
Does not expand center section when left blocks are docked

### ISSUE THREAD

**Issue by cborn** [gjb2048/moodle-theme_essential#732] opened 2016-08-29 17:47 UTC
We have the traditional course page layout with blocks on both the left and the right.  When someone docks all of the left blocks, the course page does not expand to use that space (like it does with the More theme).  However, if you dock all of the blocks on the right the center section does expand to the right.  

![screen shot 2016-08-29 at 12 46 34 pm](https://cloud.githubusercontent.com/assets/1149264/18061010/a6bdb6b2-6de6-11e6-9eaa-95f1922eaa26.png)

**Comment by cborn** [comment] 2016-08-29 17:48
I should add that this is the case even when I do not have a block on top in the middle section.

**Comment by gjb2048** [comment] 2016-08-29 17:58
What version of the theme are you using?  I suspect this is a duplicate of the fixed #724.

**Comment by gjb2048** [comment] 2016-08-29 17:59
Or the fixed #711.

**Comment by cborn** [comment] 2016-08-29 18:19
Sorry, I looked through the existing bugs and didn't seem to find the same thing. 

I'm using 3.1.0.6 (Build: 2016061705)

**Comment by cborn** [comment] 2016-08-29 18:20
Moodle is version 3.1.1 (Build: 20160711)

**Comment by gjb2048** [comment] 2016-08-29 19:20
Ah, existing bug but in the closed list: https://github.com/gjb2048/moodle-theme_essential/issues?q=is%3Aissue+is%3Aclosed

**Closed by gjb2048** 2016-08-29 19:20 UTC
Labels: Information required
