### ISSUE TITLE
Missing icons and icons not working

### ISSUE THREAD

**Issue by Naomi-Mifsud** [gjb2048/moodle-theme_essential#709] opened 2016-08-05 08:21 UTC
Hi,
We have recently installed the latest theme Essential plugin on Moodle 3.1.1. While testing, we have noticed that some icons are not being displayed when using Moodle Assignment. While some other icons are partly hidden and not functioning as expected.

We have also tested Moodle Assignment with a different theme to make sure whether it was the new Assignment display which was not working, or the theme. However, when we tested with the Clean theme all icons were displayed and working as required. Please refer to the screenshots below.

Moodle Assignment with Essential:
![essentialthemebugreport01](https://cloud.githubusercontent.com/assets/20833815/17430690/109385f2-5af6-11e6-827b-07f9aeeae7d3.png)

Moodle Assignment with Clean:
![essentialthemebugreport02](https://cloud.githubusercontent.com/assets/20833815/17430694/1b5161bc-5af6-11e6-9d83-7df84b585289.png)

Can you please provide us with some insight with respect to this issue.

Much thanks in advance,
Naomi

**Comment by gjb2048** [comment] 2016-08-05 09:07
Fixed in next version, not released on Moodle plugins DB yet.

**Comment by Naomi-Mifsud** [comment] 2016-08-05 09:09
Much thanks for your prompt attention.

**Comment by gjb2048** [comment] 2016-08-08 15:26
Duplicate of #699.

**Closed by gjb2048** 2016-08-08 15:26 UTC
Labels: Bug, Duplicate
