### ISSUE TITLE
Unable to close Message box after sending message.

### ISSUE THREAD

**Issue by jonfila** [gjb2048/moodle-theme_essential#502] opened 2015-06-05 14:25 UTC
When viewing a profile and clicking on Message, the box opens, I type my message and hit Send message. I can verify that the message sends but when I click on the x to close the box it does not close. The only way out of the page is to click another link or go back in the browser.

![screen shot 2015-06-05 at 9 24 23 am](https://cloud.githubusercontent.com/assets/8570031/8007985/db906d48-0b64-11e5-9d8b-f85d37a07c3c.png)

**Comment by gjb2048** [comment] 2015-06-05 14:30
What version of Moodle and Essential please?

**Comment by jonfila** [comment] 2015-06-05 14:37
My apologies!
Moodle 2.9
Essential: 2.8.1.4 (Build: 2015040900)

**Comment by gjb2048** [comment] 2015-06-05 14:42
Moodle 2.9 is not supported by the M2.8 version as clearly stated in the Readme.txt file: https://github.com/gjb2048/moodle-theme_essential/blob/master/README.txt#L88-L91

I'll not look at any possible issues until I get around to making the M2.9 version: https://github.com/gjb2048/moodle-theme_essential/milestones/Moodle%202.9%20version - that will depend on any remaining M2.8 issues being resolved first.

**Comment by jonfila** [comment] 2015-06-05 14:44
I understand. Just wanted you to be aware of it.

**Comment by gjb2048** [comment] 2015-06-05 14:46
Umm, thanks!

**Comment by gjb2048** [comment] 2015-06-13 12:30
Missing class 'core_message-messenger-sendmessage-hidden' from core Moodle LESS.  Will be added when create Moodle 2.9 version as a part of that already planned process.

**Comment by gjb2048** [comment] 2015-06-13 12:32
Removed 'Bug' as not a bug as would not have been a problem when M2.9 version produced.  Therefore as M2.9 version is an enhancement, so is this.

**Comment by gjb2048** [comment] 2015-06-13 12:34
And the moral of this story is 'don't use software designed for an older version that is stated not to be used on the newer version'.  Spent a little while trying to see what is going on here.  Waisted time.  Not happy.  If had been a 'bug' in 'official' M2.9 test / production version, then fine, really not happy.

**Comment by jonfila** [comment] 2015-06-13 13:50
Thank you for the lesson Sifu.

**Comment by gjb2048** [comment] 2015-06-24 18:01
Fixed in: https://github.com/gjb2048/moodle-theme_essential/releases/tag/V2.9.0.1

**Closed by gjb2048** 2015-06-24 18:01 UTC
Labels: Enhancement, Not a bug
