### ISSUE TITLE
Gradebook Tabs Not Left Justified

### ISSUE THREAD

**Issue by pccde** [gjb2048/moodle-theme_essential#515] opened 2015-07-20 14:25 UTC
If you have a gradebook with many items, the edit tabs center themselves on the width of the gradebook, rather than being left justified for easy access.  If you are viewing the gradebook at normal view, one might think the tabs are not showing.  Attached image is zoomed out for illustration:

![gradebook_tabs](https://cloud.githubusercontent.com/assets/12518238/8778023/7717b6a4-2ec9-11e5-9fe1-768f8d84031c.png)

**Comment by mkpelletier** [comment] 2015-07-20 14:28
I can confirm this on my install as well.  Gareth will want to know the version of Moodle and version of essential you are using.  As for me, Gareth, here are my details:

Moodle: 2.8.6+ (20150625)
Essential: 2.8.1.5 (Build: 2015040900)

Best Regards,

**Comment by gjb2048** [comment] 2015-07-20 15:05
Ta.  What does it look like in Clean?

**Comment by gjb2048** [comment] 2015-07-20 15:57
Cannot get the tabs to show....

![2015-07-20 16_54_58-grades_ view](https://cloud.githubusercontent.com/assets/1058419/8780364/607587b4-2f00-11e5-8191-267cd69fcbf1.jpg)

How do I replicate this?  Could you supply a test course please.

**Comment by pccde** [comment] 2015-07-20 18:00
We are using Moodle 2.8.5 and Essential 2.8.1.4 (Build: 2015040900).  This does not happen with the Clean theme.  I will see if I can create a test course for you to view on our Public site.

**Comment by ActionJONA** [comment] 2015-07-22 07:57
Hi Gareth, you should be able to change it under the 'Navigation method' found here:

Site admin - Grades - General Settings

or

"your moodle" /admin/settings.php?section=gradessettings

**Comment by gjb2048** [comment] 2015-07-22 08:56
Ta.

**Comment by gjb2048** [comment] 2015-07-22 16:49
Ok, this has been there since the dawn of time: https://github.com/eduridden/moodle-theme_essential/blob/master/style/essential.css#L1549-L1551 - I have no idea why.

**Comment by gjb2048** [comment] 2015-07-23 12:07
Fixed in: https://github.com/gjb2048/moodle-theme_essential/commit/0bd49a5c87c463429578f61a00258318488bbd38

**Closed by gjb2048** 2015-07-23 12:07 UTC
Labels: Pending replication

**Comment by pccde** [comment] 2015-07-23 13:21
Gareth:

Thank you for fixing this.  Will this be available in the Moodle 2.8.x version of Essential or will I have to go to 2.9 to get the update?

**Comment by gjb2048** [comment] 2015-07-23 14:31
M2.8 yes.
