### ISSUE TITLE
Course page layout strange when no blocks on right

### ISSUE THREAD

**Issue by cborn** [gjb2048/moodle-theme_essential#733] opened 2016-08-29 21:25 UTC
Hopefully this is not a duplicate of another issue, I tried to look carefully this time.

On our course pages, if you do not have any blocks on the right the main course page looks strange.  If you enter an activity, the center sections expand fully to the right as expected.  But the main course page makes both the left block column and the center section width more restricted than normal.  

We believe this may have been introduced with our update to the current 3.1.0.7 (Build: 2016061706) in the last hour or two.  We are using Moodle 3.1.1.

This is the display issue:
![screen shot 2016-08-29 at 4 24 09 pm](https://cloud.githubusercontent.com/assets/1149264/18068050/25ca7544-6e05-11e6-8352-92d8edea0963.png)

Same issue does not appear when you enter an assignment (or any other activity):
![screen shot 2016-08-29 at 4 24 17 pm](https://cloud.githubusercontent.com/assets/1149264/18068062/3b9c2b56-6e05-11e6-872b-bfbe40e00b0f.png)

**Comment by gjb2048** [comment] 2016-08-29 21:32
Hi Carly,

Ok, thank you for the issue, however it is a duplicate of #724 which I have fixed in the forthcoming 3.1.0.8 which has not been released on Moodle.org yet (please see: https://moodle.org/mod/forum/discuss.php?d=338901#p1365687 for reasons).

The reason you are seeing what you are seeing is because the 'course' layout has a three column layout and the 'incourse' layout only two.

Kind regards,

Gareth

**Closed by gjb2048** 2016-08-29 21:32 UTC
Labels: Bug, Duplicate

**Comment by cborn** [comment] 2016-08-30 00:12
Thank you for you amazingly quick responses!!  I appreciate all that you do to make this theme awesome!!
