### ISSUE TITLE
Show/Hide icon does not change

### ISSUE THREAD

**Issue by pccde** [gjb2048/moodle-theme_essential#509] opened 2015-06-11 19:41 UTC
Show/Hide icon works, but does not change to reflect it's status.  Works fine for Show/Hide on blocks.  Works fine with the Clean theme.
![show-hide](https://cloud.githubusercontent.com/assets/12518238/8116452/4b32fc5c-1050-11e5-878f-4450957759d6.png)

**Comment by gjb2048** [comment] 2015-06-11 19:56
Because Essential uses an icon font to substitute images for font glyphs here: https://github.com/gjb2048/moodle-theme_essential/blob/master/renderers/core_renderer.php#L986-L987 and yet the Moodle core code JavaScript manipulates the 'img' icon image directly rather than changing a CSS class then the theme is unable to implement a solution where this icon can change in response to the AJAX request / response mechanism that drives it.  Therefore this is currently impossible to fix.  Please see: https://tracker.moodle.org/browse/MDL-40759.

**Comment by gjb2048** [comment] 2015-06-11 19:59
Unless.... the AJAX returns some HTML and then it might be possible, but I don't think it does.  In fact I think the AJAX is just in concept one way.

**Comment by pccde** [comment] 2015-06-11 20:09
It is interesting that it works for the block editing icons but not for the
course content editing icons...


Mike Clendenen, A.A.S., IC3
 Director of Distance Learning and Instructional Technology
Pitt Community College-VEW 20
P O Drawer 7007
Greenville, NC 27835-7007
Phone: 252-493-7608
 Email: mwclendenen091@my.pittcc.edu

**Comment by gjb2048** [comment] 2015-06-11 20:17
1. Its not that interesting!
2. You mean the section editing icons not block.
3. They are the the 'img' version despite of: https://github.com/gjb2048/moodle-theme_essential/blob/master/renderers/core_renderer.php#L958 - this is because they are directly injected by the JavaScript and don't use a CSS class as previously mentioned = horrible code.

**Comment by pccde** [comment] 2015-06-11 20:19
I understand.  Is there a simple way to have the essential theme use the
default icons?


Mike Clendenen, A.A.S., IC3
 Director of Distance Learning and Instructional Technology
Pitt Community College-VEW 20
P O Drawer 7007
Greenville, NC 27835-7007
Phone: 252-493-7608
 Email: mwclendenen091@my.pittcc.edu

**Comment by gjb2048** [comment] 2015-06-11 20:21
Probably by removing this:https://github.com/gjb2048/moodle-theme_essential/blob/master/renderers/core_renderer.php#L928-L1003 - but only a guess.  If I did this then I'd get complaints, if I don't then I get complaints = Catch-22 without Major Major to blame!

**Comment by pccde** [comment] 2015-06-11 20:23
I'll give it a try.

Thanks,


Mike Clendenen, A.A.S., IC3
 Director of Distance Learning and Instructional Technology
Pitt Community College-VEW 20
P O Drawer 7007
Greenville, NC 27835-7007
Phone: 252-493-7608
 Email: mwclendenen091@my.pittcc.edu

**Comment by nzn-openapp** [comment] 2015-11-03 17:33
How about:
```
.editing_hide .fa-eye-slash:before {
    content: "\f06e";
}
 
.editing_show .fa-eye:before {
    content: "\f070";
}
```
Somewhere in moodle/course.less I would imagine.

**Comment by gjb2048** [comment] 2015-11-03 18:04
Interesting solution, thanks.

**Comment by gjb2048** [comment] 2015-11-03 18:22
Hopefully fixed in: https://github.com/gjb2048/moodle-theme_essential/commit/3058538c9e7b3bdea2df1053856f6a92b846b1d3

**Closed by gjb2048** 2015-11-03 18:22 UTC
Labels: Bug

**Comment by pccde** [comment] 2016-11-09 21:26
Gareth:

It's been awhile since we talked.  I hope all is going well.  In the
Essentials Theme (3.0.1.2) we notice that when you create a hyperlink, like
in a label, the link is not easy to notice.  It looks just like the
surrounding text.  Only when you mouse over it do you notice it is a link.
I know we can make it blue and underline, but is there a setting in the
Essentials theme to do that by default?  I have switched to the Clean theme
and it works, so I know it has something to do with the Essentials theme.

Any assistance would be appreciated.


Mike Clendenen, A.A.S., IC3
Director of Distance Learning and Instructional Technology
Pitt Community College-VEW 20
P O Drawer 7007
Greenville, NC 27835-7007
Phone: 252-493-7608
Email: mwclendenen091@my.pittcc.edu

**Comment by gjb2048** [comment] 2016-11-10 19:43
New issue created as this one is something else and indeed 'closed': https://github.com/gjb2048/moodle-theme_essential/issues/790

**Comment by gjb2048** [comment] 2016-11-10 20:11
Hi Mike,

Cannot reproduce in forthcoming 3.0.1.13.

Gareth

**Comment by pccde** [comment] 2016-11-10 20:40
When might that be released?


Mike Clendenen, A.A.S., IC3
Director of Distance Learning and Instructional Technology
Pitt Community College-VEW 20
P O Drawer 7007
Greenville, NC 27835-7007
Phone: 252-493-7608
Email: mwclendenen091@my.pittcc.edu

**Comment by gjb2048** [comment] 2016-11-10 20:44
From the perspective of this issue, 3.0.1.13 is currently the same as the released 3.0.1.12: https://github.com/gjb2048/moodle-theme_essential/compare/V3.0.1.12...MOODLE_30 - therefore no bug to fix or release to release.

**Comment by pccde** [comment] 2016-11-10 21:03
I will upgrade to 3.0.1.12 and see how it goes.  Thanks.


Mike Clendenen, A.A.S., IC3
Director of Distance Learning and Instructional Technology
Pitt Community College-VEW 20
P O Drawer 7007
Greenville, NC 27835-7007
Phone: 252-493-7608
Email: mwclendenen091@my.pittcc.edu

**Comment by pccde** [comment] 2016-11-10 21:06
Gareth:

Thought you would get a kick out of seeing our version of Essentials:

[image: Inline image 1]

We have three different Moodle sites, one is blue, one is red and one is
green...


Mike Clendenen, A.A.S., IC3
Director of Distance Learning and Instructional Technology
Pitt Community College-VEW 20
P O Drawer 7007
Greenville, NC 27835-7007
Phone: 252-493-7608
Email: mwclendenen091@my.pittcc.edu

**Comment by gjb2048** [comment] 2016-11-10 21:13
No image :(

**Comment by pccde** [comment] 2016-11-10 21:19
Try this...


Mike Clendenen, A.A.S., IC3
Director of Distance Learning and Instructional Technology
Pitt Community College-VEW 20
P O Drawer 7007
Greenville, NC 27835-7007
Phone: 252-493-7608
Email: mwclendenen091@my.pittcc.edu

**Comment by gjb2048** [comment] 2016-11-10 21:20
Nope.

**Comment by pccde** [comment] 2016-11-10 21:28
How abou tthis:

https://drive.google.com/file/d/0B9aVHD70OxN9TGtLdUNURlB1MTg/view?usp=sharing




Mike Clendenen, A.A.S., IC3
Director of Distance Learning and Instructional Technology
Pitt Community College-VEW 20
P O Drawer 7007
Greenville, NC 27835-7007
Phone: 252-493-7608
Email: mwclendenen091@my.pittcc.edu

**Comment by gjb2048** [comment] 2016-11-10 21:29
Nice blue!

**Comment by pccde** [comment] 2016-11-10 21:57
Thanks.


Mike Clendenen, A.A.S., IC3
Director of Distance Learning and Instructional Technology
Pitt Community College-VEW 20
P O Drawer 7007
Greenville, NC 27835-7007
Phone: 252-493-7608
Email: mwclendenen091@my.pittcc.edu
