### ISSUE TITLE
Block Editing button on Plugin overview pagechanges colour on hover

### ISSUE THREAD

**Issue by zahrah-** [gjb2048/moodle-theme_essential#609] opened 2016-02-04 01:29 UTC
Hello,

Thanks for the updates to Essential!

Re: Moodle 2.9.2+ (Build: 20151002),  Essential 2.9.1.7 (Build: 2015062420)
and Moodle 3.0.1+ (Build: 20160107), Essential 3.0.0.3 (Build: 2016010202)

The "Blocks editing on" button on the Plugins Overview page, sort of changes to 2 colours when the mouse hovers on it as shown:

Essential 2.9 ....
![pluginbutton1](https://cloud.githubusercontent.com/assets/8460383/12802880/6ea4eb2e-cabc-11e5-85c2-5097075aa86e.png)

Essential 3....
![pluginbutton2](https://cloud.githubusercontent.com/assets/8460383/12802892/7ed82af6-cabc-11e5-9fb9-b827ac6d1a06.png)

Regards,
sali

**Comment by gjb2048** [comment] 2016-02-04 09:34
Ok, what web browsers used and default button text and colour setting values used please?

**Comment by gjb2048** [comment] 2016-02-04 09:35
And web browser versions?

**Comment by gjb2048** [comment] 2016-02-04 10:04
Did you also update using Site administration -> Notifications?  This triggers the new default setting values to be set.

**Comment by gjb2048** [comment] 2016-02-04 10:45
And why are the buttons different between versions when the code and default setting values are the same?

**Comment by sympo** [comment] 2016-02-04 11:01
I had a similar issue when I was customizing the colours of Essential buttons some months ago and it looks like zahrah- has overwritten/is for some reason missing `background-repeat: repeat-x;`. 
I can replicate this in 2.9.1.6 by disabling `background-repeat: repeat-x;` for `.btn` and `.btn-danger` in the page inspector so it looks like they have some css which overwrites this, especially since they also seem to have styled the buttons to a non-default look.

**Comment by gjb2048** [comment] 2016-02-04 11:51
P.s. in that case, what custom CSS do you have added?

**Comment by sympo** [comment] 2016-02-04 11:58
I was styling the hamburger buttons to make the menu one look different than the social media icons and have added:

```
.navbar .btn-navbar {
background-color: #1c57f9 !important;
background-repeat: repeat-x;
background-image: none;
} 
```
Without `background-repeat: repeat-x; background-image: none;` I had the same issue as zahrah-.

**Comment by gjb2048** [comment] 2016-02-04 12:08
That CSS does not make sense from a hover persepective.

**Comment by sympo** [comment] 2016-02-04 12:15
Sure, that's why I said it was a similar issue. The result of omitting `background-repeat: repeat-x;` was that only a half of the button was coloured so I suggest zahrah- checks that.

**Comment by gjb2048** [comment] 2016-02-04 12:22
But that attribute only affects I image values.

**Comment by zahrah-** [comment] 2016-02-04 14:13
Hello,

Sorry for delayed response (time difference...)
Here are the responses:

Browser: Firefox 44.0

Moodle 2.9
Default button text hover colour: #ffffff
Default button background colour: #048AD2
Default button background hover colour: #03A07C

Moodle 3.0
Default button text hover colour: #ffffff
Default button background colour: #E07600
Default button background hover colour: #9FAA00

Yes, updated using Site Admin-> Notifications

Colours are different between versions becasuse they are two differemt Moodle installs coloured differently so it's easier for me to not mix them up during testing.

Just tested with Chrome as well. Version 48.0.2564.103 m

Just noticed that the same effect occurs with the social icons (looks like a special effect).

If you need any additional info let me know.

Regards,
sali

**Comment by zahrah-** [comment] 2016-02-04 14:14
Forgot to mention that issue persists with Chrome as well,

**Comment by zahrah-** [comment] 2016-02-04 14:18
Removed all custom CSS and purged cache - issue persists.

**Comment by ghrich** [comment] 2016-02-04 14:47
Hi Gareth,

I've just installed Essential 2.9.1.7 and can confirm the above issue.

I am running Moodle 2.9.4+

Have tested in latest versions of IE, Chrome and FF and the issue is the same in all of them.

The buttons I have noticed this happening with are 'Blocke Editing', 'Customise this page' and the social/app icons.

![button2](https://cloud.githubusercontent.com/assets/8349855/12818293/25d49d3a-cb4e-11e5-8149-5324d870c7a3.png)
![button1](https://cloud.githubusercontent.com/assets/8349855/12818292/25d213b2-cb4e-11e5-9747-c5addd0d5c7a.png)
![apps](https://cloud.githubusercontent.com/assets/8349855/12818294/25d7afca-cb4e-11e5-848d-8aeeab156ce5.png)

Thanks for all your hard work as always!

Richard

**Comment by ghrich** [comment] 2016-02-04 14:54
I should add, this behaviour is not seen on all buttons. The 'Search', 'Check for available updates', 'Add filter', 'Add user' etc are working as expected.

I do remember, the buttons displayed above did exhibit slightly different behaviour before I performed this upgrade. I think when hovering over them they were a contrasting colour (similar to those in the status homepage blocks). The buttons that work correctly are buttons that have always seemed to conform to a more standard Moodle CMS theme style.

**Comment by gjb2048** [comment] 2016-02-04 17:36
Background repeat has didly squat to do with it.  Fixed in: https://github.com/gjb2048/moodle-theme_essential/commit/4141eee89357fc14c19bb5ea184893c140364266 - will back-port to M2.9 in due course.

**Closed** 2016-02-04 17:35 UTC
Labels: Bug

**Comment by gjb2048** [comment] 2016-02-04 17:36
Thanks to all that pointed out where I needed to test :)
